### ISSUE TITLE
HallucinIce does not give new enemies

### ISSUE THREAD

**Issue by Hjax** [SoyGema/pySC2-minigames#2]
Sometimes when you kill all of the hellions, the next round does not start. 

This was a bug in some of the deepmind maps, and it was caused by the last two remaining enemy units dying on the same frame.

**Comment by SoyGema** [comment]
Thanks for the observation @Hjax !
will check it out !

**Comment by SoyGema** [comment]
Ey @Hjax !
Just upload a new version of HallucinIce map.
Tested with random agent for 100 episodes and scripted agent for 75 episodes.

No bug found from now with this new version.
Please, if you do find a problem in this new version let me know

Thanks again for passing by and testing mini-games 
gl&hf!

**Comment by Hjax** [comment]
The new map seems to have even more issues:
The sentries no longer start with enough energy to hallucinate anything.
When the map first loads, you have a 30 second time limit, but when you reset you have 60.

I can't test if the bug I originally mentioned was fixed because it is no longer possible to beat the levels

**Comment by SoyGema** [comment]
--Now it should work the sentry energy
--Ok I've already changed the time limit issues .

can you test it now? thanks for your patience. 
Do you mind if I add your GitHub user to the readme as tester contributor ?

**Comment by SoyGema** [comment]
Ok. Tested in double episodes and no bug found .
Please, if found send replay .
thanks !

**Comment by SoyGema** [comment]
I am closing this issue. 
If you see something significant let me know!
thanks
